spring.application.name=carrental



# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/carrental_dev
spring.datasource.username=appuser
spring.datasource.password=apppass
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA/Hibernate Configuration
#spring.jpa.hibernate.ddl-auto=validate  # for production
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# Temporary for first run - will create schema
spring.sql.init.mode=always

# Flyway Configuration
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration

# Server Configuration
server.port=8080

# For development - will show more details
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

