package com.stackclonell.stackclone.service;

import com.vladsch.flexmark.html.HtmlRenderer;
import com.vladsch.flexmark.parser.Parser;
import com.vladsch.flexmark.util.data.MutableDataSet;
import org.springframework.stereotype.Service;
import org.owasp.html.PolicyFactory;
import org.owasp.html.Sanitizers;
import com.vladsch.flexmark.util.ast.Node;  // ✅ CORRECT import


/**
 * Utility Service for Markdown conversion and Security Input Sanitization.
 * Addresses the 'Input Sanitization' security requirement.
 */
@Service
public class MarkdownService {

    private final Parser parser;
    private final HtmlRenderer renderer;
    private final PolicyFactory htmlSanitizer;

    public MarkdownService() {
        // Flexmark configuration: Options for parsing (e.g., enable code fences)
        MutableDataSet options = new MutableDataSet();
        // Enables extensions commonly used on Stack Overflow (e.g., code fences)
        options.set(com.vladsch.flexmark.parser.Parser.EXTENSIONS, java.util.Arrays.asList(
                com.vladsch.flexmark.ext.gfm.strikethrough.StrikethroughExtension.create(),
                com.vladsch.flexmark.ext.tables.TablesExtension.create(),
                com.vladsch.flexmark.ext.gfm.code.fence.CodeFenceExtension.create()
        ));

        // Initialize the parser and renderer
        this.parser = Parser.builder(options).build();
        this.renderer = HtmlRenderer.builder(options).build();

        // Security: Initialize OWASP HTML Sanitizer
        // Only allow safe HTML tags/attributes typically generated by Markdown
        this.htmlSanitizer = Sanitizers.FORMATTING
                .and(Sanitizers.LINKS)
                .and(Sanitizers.IMAGES)
                .and(Sanitizers.BLOCKS)
                .and(Sanitizers.TABLES) // For markdown tables
                .and(Sanitizers.STYLES); // Allow basic styles/classes for code blocks
    }

    /**
     * Converts raw Markdown to sanitized HTML.
     * @param markdownText The raw input text from the user.
     * @return The safe HTML string.
     */
    public String renderMarkdown(String markdownText) {
        if (markdownText == null || markdownText.isEmpty()) {
            return "";
        }

        // 1. Convert Markdown to raw HTML
        com.vladsch.flexmark.ast.Node document = parser.parse(markdownText);
        String rawHtml = renderer.render(document);

        // 2. Security: Sanitize the raw HTML to prevent XSS (Input Sanitization)
        // This removes any dangerous tags like <script> or malicious attributes.
        String safeHtml = htmlSanitizer.sanitize(rawHtml);

        return safeHtml;
    }
}